// airports.js
export const airports = [
    { iata: "TPE", icao: "RCTP", city: "Taipei", country: "Taiwan", name: "Taiwan Taoyuan International", lat: 25.0777, lon: 121.2328 },
    { iata: "AMS", icao: "EHAM", city: "Amsterdam", country: "Netherlands", name: "Schiphol", lat: 52.3086, lon: 4.7639 },
    { iata: "CDG", icao: "LFPG", city: "Paris", country: "France", name: "Charles de Gaulle", lat: 49.0097, lon: 2.5479 },
    { iata: "JFK", icao: "KJFK", city: "New York", country: "USA", name: "John F. Kennedy International", lat: 40.6398, lon: -73.7789 },
    { iata: "LAX", icao: "KLAX", city: "Los Angeles", country: "USA", name: "Los Angeles International", lat: 33.9425, lon: -118.4081 },
    { iata: "SFO", icao: "KSFO", city: "San Francisco", country: "USA", name: "San Francisco International", lat: 37.6188, lon: -122.3754 },
    { iata: "YYZ", icao: "CYYZ", city: "Toronto", country: "Canada", name: "Toronto Pearson International", lat: 43.6772, lon: -79.6306 },
    { iata: "GRU", icao: "SBGR", city: "São Paulo", country: "Brazil", name: "São Paulo/Guarulhos–Governador André Franco Montoro International", lat: -23.4356, lon: -46.4731 },
    { iata: "NRT", icao: "RJAA", city: "Tokyo", country: "Japan", name: "Narita International", lat: 35.7647, lon: 140.3864 },
    { iata: "ICN", icao: "RKSI", city: "Seoul", country: "South Korea", name: "Incheon International", lat: 37.4691, lon: 126.4505 },
    { iata: "SIN", icao: "WSSS", city: "Singapore", country: "Singapore", name: "Changi", lat: 1.3644, lon: 103.9915 },
    { iata: "JNB", icao: "FAOR", city: "Johannesburg", country: "South Africa", name: "O. R. Tambo International", lat: -26.1392, lon: 28.246 },
    { iata: "CPT", icao: "FACT", city: "Cape Town", country: "South Africa", name: "Cape Town International", lat: -33.9648, lon: 18.6017 },
    { iata: "DEL", icao: "VIDP", city: "New Delhi", country: "India", name: "Indira Gandhi International", lat: 28.5562, lon: 77.1000 },
    { iata: "BOM", icao: "VABB", city: "Mumbai", country: "India", name: "Chhatrapati Shivaji Maharaj International", lat: 19.0887, lon: 72.8678 },
    { iata: "BKK", icao: "VTBS", city: "Bangkok", country: "Thailand", name: "Suvarnabhumi", lat: 13.6900, lon: 100.7501 },
    { iata: "HKG", icao: "VHHH", city: "Hong Kong", country: "Hong Kong", name: "Hong Kong International", lat: 22.3080, lon: 113.9185 },
    { iata: "DXB", icao: "OMDB", city: "Dubai", country: "United Arab Emirates", name: "Dubai International", lat: 25.2532, lon: 55.3657 },
    { iata: "DOH", icao: "OTHH", city: "Doha", country: "Qatar", name: "Hamad International", lat: 25.2731, lon: 51.6139 },
    { iata: "MEX", icao: "MMMX", city: "Mexico City", country: "Mexico", name: "Benito Juárez International", lat: 19.4363, lon: -99.0721 },
    { iata: "SCL", icao: "SCEL", city: "Santiago", country: "Chile", name: "Arturo Merino Benítez International", lat: -33.3930, lon: -70.7858 },
    { iata: "EZE", icao: "SAEZ", city: "Buenos Aires", country: "Argentina", name: "Ministro Pistarini International", lat: -34.8222, lon: -58.5358 },
    { iata: "LIM", icao: "SPJC", city: "Lima", country: "Peru", name: "Jorge Chávez International", lat: -12.0219, lon: -77.1143 },
    { iata: "BOG", icao: "SKBO", city: "Bogotá", country: "Colombia", name: "El Dorado International", lat: 4.7016, lon: -74.1469 },
    { iata: "PTY", icao: "MPTO", city: "Panama City", country: "Panama", name: "Tocumen International", lat: 9.0713, lon: -79.3836 },
    { iata: "MNL", icao: "RPLL", city: "Manila", country: "Philippines", name: "Ninoy Aquino International", lat: 14.5086, lon: 121.0194 },
    { iata: "SYD", icao: "YSSY", city: "Sydney", country: "Australia", name: "Sydney Kingsford Smith", lat: -33.9461, lon: 151.1772 },
    { iata: "YVR", icao: "CYVR", city: "Vancouver", country: "Canada", name: "Vancouver International", lat: 49.1939, lon: -123.1845 },
    { iata: "IAD", icao: "KIAD", city: "Washington, D.C.", country: "USA", name: "Washington Dulles International", lat: 38.9445, lon: -77.4558 },
    { iata: "ATL", icao: "KATL", city: "Atlanta", country: "USA", name: "Hartsfield–Jackson Atlanta International", lat: 33.6367, lon: -84.4281 },
    { iata: "ORD", icao: "KORD", city: "Chicago", country: "USA", name: "O'Hare International", lat: 41.9786, lon: -87.9048 },
    { iata: "MIA", icao: "KMIA", city: "Miami", country: "USA", name: "Miami International", lat: 25.7959, lon: -80.2870 },
    { iata: "SEA", icao: "KSEA", city: "Seattle", country: "USA", name: "Seattle–Tacoma International", lat: 47.4490, lon: -122.3093 },
    { iata: "BOS", icao: "KBOS", city: "Boston", country: "USA", name: "Logan International", lat: 42.3643, lon: -71.0052 },
    { iata: "YUL", icao: "CYUL", city: "Montreal", country: "Canada", name: "Montréal–Trudeau International", lat: 45.4706, lon: -73.7408 },
    { iata: "CUN", icao: "MMUN", city: "Cancún", country: "Mexico", name: "Cancún International", lat: 21.0365, lon: -86.8771 },
    { iata: "HAV", icao: "MUHA", city: "Havana", country: "Cuba", name: "José Martí International", lat: 22.9891, lon: -82.4091 },
    { iata: "GIG", icao: "SBGL", city: "Rio de Janeiro", country: "Brazil", name: "Rio de Janeiro–Galeão International", lat: -22.8090, lon: -43.2505 },
    { iata: "NBO", icao: "HKJK", city: "Nairobi", country: "Kenya", name: "Jomo Kenyatta International", lat: -1.3192, lon: 36.9278 },
    { iata: "ACC", icao: "DGAA", city: "Accra", country: "Ghana", name: "Kotoka International", lat: 5.6052, lon: -0.1667 },
    { iata: "LOS", icao: "DNMM", city: "Lagos", country: "Nigeria", name: "Murtala Muhammed International", lat: 6.5774, lon: 3.3211 },
    { iata: "PEK", icao: "ZBAA", city: "Beijing", country: "China", name: "Beijing Capital International", lat: 40.0801, lon: 116.5845 },
    { iata: "PVG", icao: "ZSPD", city: "Shanghai", country: "China", name: "Shanghai Pudong International", lat: 31.1434, lon: 121.8053 },
    { iata: "HND", icao: "RJTT", city: "Tokyo", country: "Japan", name: "Haneda Airport (Tokyo International Airport)", lat: 35.5523, lon: 139.7797 },
    { iata: "KUL", icao: "WMKK", city: "Kuala Lumpur", country: "Malaysia", name: "Kuala Lumpur International", lat: 2.7456, lon: 101.7099 },
    { iata: "CGK", icao: "WIII", city: "Jakarta", country: "Indonesia", name: "Soekarno–Hatta International", lat: -6.1256, lon: 106.6559 },
    { iata: "SGN", icao: "VVTS", city: "Ho Chi Minh City", country: "Vietnam", name: "Tan Son Nhat International", lat: 10.8188, lon: 106.6519 },
    { iata: "BLR", icao: "VOBL", city: "Bengaluru", country: "India", name: "Kempegowda International Airport Bengaluru", lat: 13.1986, lon: 77.7066 },
    { iata: "IAH", icao: "KIAH", city: "Houston", country: "USA", name: "George Bush Intercontinental", lat: 29.9844, lon: -95.3414 },
    { iata: "DFW", icao: "KDFW", city: "Dallas-Fort Worth", country: "USA", name: "Dallas Fort Worth International", lat: 32.8968, lon: -97.0380 },
    { iata: "MSP", icao: "KMSP", city: "Minneapolis", country: "USA", name: "Minneapolis–Saint Paul International Airport", lat: 44.8820, lon: -93.2218 },
    { iata: "DTW", icao: "KDTW", city: "Detroit", country: "USA", name: "Detroit Metropolitan Wayne County", lat: 42.2124, lon: -83.3534 },
    { iata: "SLC", icao: "KSLC", city: "Salt Lake City", country: "USA", name: "Salt Lake City International Airport", lat: 40.7884, lon: -111.9778 },
    { iata: "YYC", icao: "CYYC", city: "Calgary", country: "Canada", name: "Calgary International", lat: 51.1139, lon: -114.0203 },
    { iata: "ABJ", icao: "DIAP", city: "Abidjan", country: "Ivory Coast", name: "Félix-Houphouët-Boigny International", lat: 5.2614, lon: -3.9263 },
    { iata: "CAI", icao: "HECA", city: "Cairo", country: "Egypt", name: "Cairo International", lat: 30.1219, lon: 31.4056 },
    { iata: "DAR", icao: "HTDA", city: "Dar es Salaam", country: "Tanzania", name: "Julius Nyerere International", lat: -6.8781, lon: 39.2026 },
    { iata: "KGL", icao: "HRYR", city: "Kigali", country: "Rwanda", name: "Kigali International Airport", lat: -1.9686, lon: 30.1395 },
    { iata: "EBB", icao: "HUEN", city: "Entebbe", country: "Uganda", name: "Entebbe International Airport", lat: 0.0424, lon: 32.4435 },
    { iata: "RUH", icao: "OERK", city: "Riyadh", country: "Saudi Arabia", name: "King Khalid International", lat: 24.9576, lon: 46.6988 },
    { iata: "SXM", icao: "TNCM", city: "Philipsburg", country: "Sint Maarten", name: "Princess Juliana International Airport", lat: 18.0409, lon: -63.1089 },
    { iata: "CUR", icao: "TNCC", city: "Willemstad", country: "Curaçao", name: "Hato International Airport", lat: 12.1889, lon: -68.9597 }
  ];
  
  